CREATE TABLE IF NOT EXISTS employer_settings (
  employer_id BIGINT UNSIGNED PRIMARY KEY,
  billing_plan VARCHAR(128) DEFAULT 'free',
  credits INT DEFAULT 0,
  timezone VARCHAR(64) DEFAULT 'Asia/Kolkata',
  notification_pref JSON DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (employer_id) REFERENCES employers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

