CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  employer_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description LONGTEXT NOT NULL,
  short_description VARCHAR(1000) NULL,
  employment_type ENUM('full_time','part_time','contract','internship','freelance') DEFAULT 'full_time',
  seniority ENUM('entry','mid','senior','lead','manager') DEFAULT 'mid',
  salary_min INT NULL,
  salary_max INT NULL,
  currency VARCHAR(8) DEFAULT 'INR',
  is_remote TINYINT(1) DEFAULT 0,
  locations JSON NULL,
  status ENUM('draft','published','paused','closed','archived') DEFAULT 'draft',
  visibility ENUM('public','private','internal') DEFAULT 'public',
  publish_at DATETIME NULL,
  expires_at DATETIME NULL,
  vacancies INT DEFAULT 1,
  views BIGINT UNSIGNED DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (employer_id) REFERENCES employers(id) ON DELETE CASCADE,
  INDEX (employer_id),
  INDEX (status),
  INDEX (publish_at),
  INDEX (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

