CREATE TABLE IF NOT EXISTS job_locations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  job_id BIGINT UNSIGNED NOT NULL,
  city VARCHAR(128),
  state VARCHAR(128),
  country VARCHAR(128),
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
  INDEX (city),
  INDEX (country)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

