CREATE TABLE IF NOT EXISTS employer_api_keys (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  employer_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  secret_hash VARCHAR(255) NOT NULL,
  allowed_ips TEXT NULL,
  scopes JSON DEFAULT '[]',
  revoked TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  last_used_at DATETIME NULL,
  FOREIGN KEY (employer_id) REFERENCES employers(id) ON DELETE CASCADE,
  INDEX(employer_id),
  INDEX(revoked)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS webhooks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  employer_id BIGINT UNSIGNED NOT NULL,
  url VARCHAR(1024) NOT NULL,
  events JSON NOT NULL,
  secret VARCHAR(255) NULL,
  active TINYINT(1) DEFAULT 1,
  last_delivery_at DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employer_id) REFERENCES employers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

