ALTER TABLE interviews ADD COLUMN IF NOT EXISTS is_premium TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS started_at DATETIME NULL;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS ended_at DATETIME NULL;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS recording_url VARCHAR(2048) NULL;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS created_by_role VARCHAR(32) NULL;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS room_name VARCHAR(128) NULL;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS room_password_enc TEXT NULL;
