-- Jobsence ₹155 registrations: skill, internship, full-time, part-time, WFH, mentors/institutes
-- Also auto-created by App\Models\PortalRegistration::ensureSchema()
CREATE TABLE IF NOT EXISTS portal_registrations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reg_no VARCHAR(20) NULL,
    token CHAR(32) NOT NULL,
    type ENUM('skill','internship','fulltime','parttime','wfh','provider') NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    dob DATE NULL,
    gender ENUM('male','female','other') NULL,
    mobile VARCHAR(15) NOT NULL,
    whatsapp VARCHAR(15) NULL,
    email VARCHAR(190) NULL,
    aadhaar_last4 CHAR(4) NULL,
    gstin VARCHAR(15) NULL,
    district VARCHAR(120) NULL,
    city VARCHAR(120) NULL,
    state VARCHAR(80) NULL,
    pincode CHAR(6) NULL,
    qualification VARCHAR(40) NULL,
    categories TEXT NULL,
    preferred_location VARCHAR(190) NULL,
    resume_path VARCHAR(255) NULL,
    video_path VARCHAR(255) NULL,
    email_verified_at DATETIME NULL,
    details JSON NULL,
    ui_language VARCHAR(10) NULL,
    declaration_accepted TINYINT(1) NOT NULL DEFAULT 0,
    fee_base DECIMAL(10,2) NOT NULL,
    gst_amount DECIMAL(10,2) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    payment_status ENUM('pending','paid','failed') NOT NULL DEFAULT 'pending',
    razorpay_order_id VARCHAR(64) NULL,
    razorpay_payment_id VARCHAR(64) NULL,
    razorpay_signature VARCHAR(190) NULL,
    paid_at DATETIME NULL,
    status ENUM('new','under_scrutiny','selected','rejected','completed') NOT NULL DEFAULT 'new',
    admin_notes TEXT NULL,
    reminder_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
    last_reminder_at DATETIME NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(255) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_portal_reg_token (token),
    KEY idx_portal_reg_no (reg_no),
    KEY idx_portal_reg_type_pay (type, payment_status),
    KEY idx_portal_reg_mobile (mobile),
    KEY idx_portal_reg_email (email),
    KEY idx_portal_reg_gstin (gstin),
    KEY idx_portal_reg_state (state),
    KEY idx_portal_reg_order (razorpay_order_id),
    KEY idx_portal_reg_reminder (payment_status, reminder_count)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
