-- Rebrand: Mindware Infotech -> Jobsence (site-owned content only).
-- BACK UP THE DATABASE FIRST. Safe to run more than once.
-- Not touched on purpose: user-written text (candidate bios, reviews, messages, resumes), historical logs/notifications,
-- other people's accounts, and URL slugs (e.g. /company/mindware-info-tech, blog slugs) so indexed links keep working.

SET NAMES utf8mb4;

UPDATE system_settings SET setting_value = 'Jobsence' WHERE setting_key = 'platform_name';
UPDATE system_settings SET setting_value = 'Jobsence – भारत का Job Portal\nभारत को कुशल बनाने की Jobsence पहल\nContact us: gm@jobsence.com\nUnsubscribe options available in your profile.' WHERE setting_key = 'email_footer' AND setting_value LIKE '%Mindware%';
UPDATE system_settings SET setting_value = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`setting_value`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence') WHERE setting_value LIKE '%mindware%' OR setting_value LIKE '%mindinfotech%';
UPDATE system_settings SET setting_value = REPLACE(setting_value, 'support@mindinfotech.com', 'gm@jobsence.com') WHERE setting_value LIKE '%mindinfotech.com%';

-- blogs
UPDATE `blogs` SET
    `title` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`title`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `excerpt` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`excerpt`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `content` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`content`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `meta_title` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`meta_title`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `meta_description` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`meta_description`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `meta_keywords` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`meta_keywords`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `canonical_url` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`canonical_url`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence')
WHERE (`title` LIKE '%mindware%' OR `title` LIKE '%jobsense%') OR (`excerpt` LIKE '%mindware%' OR `excerpt` LIKE '%jobsense%') OR (`content` LIKE '%mindware%' OR `content` LIKE '%jobsense%') OR (`meta_title` LIKE '%mindware%' OR `meta_title` LIKE '%jobsense%') OR (`meta_description` LIKE '%mindware%' OR `meta_description` LIKE '%jobsense%') OR (`meta_keywords` LIKE '%mindware%' OR `meta_keywords` LIKE '%jobsense%') OR (`canonical_url` LIKE '%mindware%' OR `canonical_url` LIKE '%jobsense%');

-- blog_tags
UPDATE `blog_tags` SET
    `name` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`name`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence')
WHERE (`name` LIKE '%mindware%' OR `name` LIKE '%jobsense%');

-- careers
UPDATE `careers` SET
    `title` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`title`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `description` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`description`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence')
WHERE (`title` LIKE '%mindware%' OR `title` LIKE '%jobsense%') OR (`description` LIKE '%mindware%' OR `description` LIKE '%jobsense%');

-- career_articles
UPDATE `career_articles` SET
    `author` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`author`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence')
WHERE (`author` LIKE '%mindware%' OR `author` LIKE '%jobsense%');

-- cookie_policy_versions
UPDATE `cookie_policy_versions` SET
    `policy_text` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`policy_text`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence')
WHERE (`policy_text` LIKE '%mindware%' OR `policy_text` LIKE '%jobsense%');

-- testimonials
UPDATE `testimonials` SET
    `title` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`title`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence')
WHERE (`title` LIKE '%mindware%' OR `title` LIKE '%jobsense%');

-- companies
UPDATE `companies` SET
    `name` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`name`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `short_name` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`short_name`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `description` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`description`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `website` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`website`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence')
WHERE (`name` LIKE '%mindware%' OR `name` LIKE '%jobsense%') OR (`short_name` LIKE '%mindware%' OR `short_name` LIKE '%jobsense%') OR (`description` LIKE '%mindware%' OR `description` LIKE '%jobsense%') OR (`website` LIKE '%mindware%' OR `website` LIKE '%jobsense%');

-- employers
UPDATE `employers` SET
    `company_name` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`company_name`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `website` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`website`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence')
WHERE (`company_name` LIKE '%mindware%' OR `company_name` LIKE '%jobsense%') OR (`website` LIKE '%mindware%' OR `website` LIKE '%jobsense%');

-- jobs
UPDATE `jobs` SET
    `company_name` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`company_name`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence')
WHERE (`company_name` LIKE '%mindware%' OR `company_name` LIKE '%jobsense%');

-- interviews
UPDATE `interviews` SET
    `meeting_link` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`meeting_link`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence')
WHERE (`meeting_link` LIKE '%mindware%' OR `meeting_link` LIKE '%jobsense%');

-- social_organizations
UPDATE `social_organizations` SET
    `organization_name` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`organization_name`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `website` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`website`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence'),
    `mission` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`mission`, 'Mindware Infotech Admin', 'Jobsence Admin'), 'MINDWARE INFOTECH', 'JOBSENCE'), 'Mindware Infotech', 'Jobsence'), 'Mindware InfoTech', 'Jobsence'), 'Mindware infotech', 'Jobsence'), 'mindware infotech', 'Jobsence'), 'Mindware info tech', 'Jobsence'), 'Mindware Info Tech', 'Jobsence'), 'support@mindwareinfotech.com', 'gm@jobsence.com'), 'sales@mindwareinfotech.com', 'gm@jobsence.com'), 'hello@mindwareinfotech.com', 'gm@jobsence.com'), 'gm@mindwareinfotech.com', 'gm@jobsence.com'), 'https://www.mindwareinfotech.com', 'https://jobsence.com'), 'http://www.mindwareinfotech.com', 'https://jobsence.com'), 'https://mindwareinfotech.com', 'https://jobsence.com'), 'www.mindwareinfotech.com', 'jobsence.com'), 'https://www.mindwareindia.com', 'https://jobsence.com'), 'www.mindwareindia.com', 'jobsence.com'), 'Mindwareinfotech', 'Jobsence'), 'MindwareInfotech', 'Jobsence'), 'Mindware', 'Jobsence'), 'Jobsense', 'Jobsence')
WHERE (`organization_name` LIKE '%mindware%' OR `organization_name` LIKE '%jobsense%') OR (`website` LIKE '%mindware%' OR `website` LIKE '%jobsense%') OR (`mission` LIKE '%mindware%' OR `mission` LIKE '%jobsense%');


-- Admin-posted jobs belong to Jobsence itself: show them as "Jobsence", not as a separate "… Admin" company.
UPDATE employers SET company_name = 'Jobsence' WHERE company_name IN ('Jobsence Admin', 'Mindware Infotech Admin');
UPDATE companies SET name = 'Jobsence', short_name = 'Jobsence' WHERE name IN ('Jobsence Admin', 'Mindware Infotech Admin');
UPDATE jobs SET company_name = 'Jobsence' WHERE company_name IN ('Jobsence Admin', 'Mindware Infotech Admin');
